const TABLE_WIDGET_SETUP_METHOD_KEYS = [
    'cellAllowsEditing',
    'cellDisplayActionClass',
    'cellDisplayActions',
    'cellDisplayActionsClass',
    'cellDisplayClass',
    'cellDisplayTextClass',
    'cellDisplayTextStyle',
    'cellSelectionOutlineStyle',
    'cellTabindex',
    'cellTdClass',
    'cellValueByIdentity',
    'cellUsesEmbeddedWidget',
    'cellUsesNativeInput',
    'cellWidgetComponent',
    'cellWidgetConfigByIdentity',
    'cellWidgetNameByIdentity',
    'cellWidgetRefNameByIdentity',
    'clearCellOverflowHint',
    'dispatchTableCommand',
    'formatCellValueByIdentity',
    'getTableEl',
    'getValue',
    'groupExpanded',
    'groupRowStyle',
    'headerThStyle',
    'hideContextMenu',
    'iconSrc',
    'initializeTable',
    'isCellEditing',
    'leafColStyle',
    'onBodyContextMenu',
    'onCellDisplayActionByIdentity',
    'onCellInputByIdentity',
    'onCellInputViewMouseDown',
    'onCellWidgetPayloadByIdentity',
    'onColumnNumberHeaderContextMenu',
    'onContextMenuItemActivate',
    'onCtxIconError',
    'onGroupHeaderContextMenu',
    'onHeaderSortClick',
    'onIpInputByIdentity',
    'onNativeCellBlur',
    'onNativeCellBlurByIdentity',
    'onTableCellClick',
    'onTableCellDblClick',
    'onTableCellMouseDown',
    'onTableContainerFocusIn',
    'onTableContainerFocusOut',
    'onTableEditableKeydown',
    'onTableHeaderContextMenu',
    'onTbodyMouseDownCapture',
    'onTextCellBlur',
    'onTextCellBlurByIdentity',
    'runtimeColumnKey',
    'setValue',
    'showSortInHeaderCell',
    'sortAriaLabel',
    'sortControlClass',
    'syncCellOverflowHint',
    'thAriaSort',
    'toggleGroupExpand'
] as const;

type TableWidgetSetupMethodKey = typeof TABLE_WIDGET_SETUP_METHOD_KEYS[number];

export { TABLE_WIDGET_SETUP_METHOD_KEYS };
export type { TableWidgetSetupMethodKey };
